import Foundation

// 這個檔案由 /tmp/hell/gen.py 從對戰表產生，請不要手改。
// 資料格式同第 5 節：每張拳只列自己的打贏清單，清單外一律算輸、同名算平手。

extension HandRuleSet {

    /// 地獄模式：19 種拳，外加每一對專屬的戰報字幕。
    static let hell = HandRuleSet(
        shapes: [
            HandShape(id: "godzilla", name: "哥吉拉", symbol: "🦖", beats: ["nuke", "love", "chickenbro", "ronaldo", "shark", "vampire", "kitten", "rock", "scissors", "paper", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "nuke", name: "核彈", symbol: "☢️", beats: ["peterpan", "chickenbro", "ronaldo", "virus", "shark", "vampire", "banana", "kitten", "rock", "scissors", "paper", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "love", name: "愛", symbol: "❤️", beats: ["nuke", "hollowpurple", "virus", "shark", "vampire", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "peterpan", name: "彼得潘", symbol: "🧚", beats: ["godzilla", "love", "ronaldo", "virus", "shark", "banana", "kitten", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "hollowpurple", name: "虛式茈", symbol: "🟣", beats: ["godzilla", "nuke", "peterpan", "chickenbro", "pooh", "ronaldo", "virus", "shark", "ufo", "vampire", "banana", "kitten", "rock", "scissors", "paper", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "chickenbro", name: "雞哥", symbol: "🐔", beats: ["love", "peterpan", "ronaldo", "banana", "kitten", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "pooh", name: "小熊維尼", symbol: "🐻", beats: ["godzilla", "nuke", "love", "peterpan", "chickenbro", "banana", "kitten", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "ronaldo", name: "C羅", symbol: "⚽️", beats: ["love", "pooh", "kitten", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "virus", name: "病毒", symbol: "🦠", beats: ["godzilla", "chickenbro", "pooh", "ronaldo", "shark", "vampire", "banana", "kitten", "rock", "scissors", "paper", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "shark", name: "鯊魚", symbol: "🦈", beats: ["chickenbro", "pooh", "ronaldo", "banana", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "ufo", name: "飛碟", symbol: "🛸", beats: ["godzilla", "nuke", "love", "peterpan", "chickenbro", "pooh", "ronaldo", "virus", "shark", "vampire", "banana", "kitten", "rock", "scissors", "paper", "lizard", "spock"], verb: "輾過"),
            HandShape(id: "vampire", name: "吸血鬼", symbol: "🧛", beats: ["peterpan", "chickenbro", "pooh", "ronaldo", "shark", "banana", "kitten", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "banana", name: "香蕉", symbol: "🍌", beats: ["godzilla", "love", "ronaldo", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "kitten", name: "小貓", symbol: "🐱", beats: ["love", "shark", "banana", "rock", "scissors", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "rock", name: "石頭", symbol: "✊", beats: ["love", "scissors", "lizard"], verb: "輾過"),
            HandShape(id: "scissors", name: "剪刀", symbol: "✌️", beats: ["love", "paper", "lizard"], verb: "輾過"),
            HandShape(id: "paper", name: "布", symbol: "✋", beats: ["love", "rock", "spock"], verb: "輾過"),
            HandShape(id: "lizard", name: "蜥蜴", symbol: "🦎", beats: ["paper", "spock"], verb: "輾過"),
            HandShape(id: "spock", name: "史巴克", symbol: "🖖", beats: ["peterpan", "chickenbro", "pooh", "ronaldo", "shark", "vampire", "banana", "kitten", "rock", "scissors"], verb: "輾過"),
        ],
        reports: [
            "godzilla|nuke": "核彈？哥吉拉表示謝謝招待！",
            "godzilla|love": "哥吉拉感受不到...",
            "godzilla|chickenbro": "哥吉拉出手，雞哥直接沒了。",
            "godzilla|ronaldo": "哥吉拉：C羅也算對手？",
            "godzilla|shark": "哥吉拉：這也算對手？",
            "godzilla|vampire": "哥吉拉一招收工，吸血鬼 GG。",
            "godzilla|kitten": "小貓被哥吉拉打到懷疑人生。",
            "godzilla|rock": "石頭被哥吉拉打到懷疑人生。",
            "godzilla|scissors": "哥吉拉一招收工，剪刀 GG。",
            "godzilla|paper": "哥吉拉完勝，布招都沒出完。",
            "godzilla|lizard": "蜥蜴：「我打哥吉拉？」",
            "godzilla|spock": "沒懸念，哥吉拉輾過史巴克。",
            "nuke|peterpan": "核彈：這也算對手？",
            "nuke|chickenbro": "雞哥打不過核彈。",
            "nuke|ronaldo": "沒懸念，核彈輾過C羅。",
            "nuke|virus": "核彈：這也算對手？",
            "nuke|shark": "沒懸念，核彈輾過鯊魚。",
            "nuke|vampire": "沒懸念，核彈輾過吸血鬼。",
            "nuke|banana": "沒懸念，核彈輾過香蕉。",
            "nuke|kitten": "核彈出手，小貓直接沒了。",
            "nuke|rock": "核彈出手，石頭直接沒了。",
            "nuke|scissors": "剪刀：不比了。",
            "nuke|paper": "這場核彈躺著贏。",
            "nuke|lizard": "核彈一招收工，蜥蜴GG。",
            "nuke|spock": "史巴克打不過核彈。",
            "love|nuke": "Make love, not war，核彈熄火。",
            "love|hollowpurple": "正負無限被真愛勸和了。虛式茈輸了。",
            "love|virus": "愛能戰勝病毒。",
            "love|shark": "鯊魚被愛感化了。",
            "love|vampire": "真愛破除詛咒，吸血鬼灰飛煙滅。",
            "love|lizard": "愛感化了蜥蜴。",
            "love|spock": "史巴克被愛感化了。",
            "peterpan|godzilla": "彼得潘應該比較強吧？",
            "peterpan|love": "彼得潘擁有很多愛。",
            "peterpan|ronaldo": "C羅贏不了欸。",
            "peterpan|virus": "彼得潘才不會生病。",
            "peterpan|shark": "彼得潘應該打的過鯊魚吧？",
            "peterpan|banana": "彼得潘會飛阿。",
            "peterpan|kitten": "小貓被彼得潘 打到懷疑人生。",
            "peterpan|rock": "石頭被彼得潘 打到懷疑人生。",
            "peterpan|scissors": "彼得潘一招收工，剪刀GG。",
            "peterpan|paper": "彼得潘出手，布直接沒了。",
            "peterpan|lizard": "蜥蜴對上彼得潘，被秒殺。",
            "hollowpurple|godzilla": "虛式茈秒殺？",
            "hollowpurple|nuke": "虛式茈煙滅了核彈。",
            "hollowpurple|peterpan": "虛式茈煙滅了彼得潘。",
            "hollowpurple|chickenbro": "雞哥 被 虛式茈 打到懷疑人生。",
            "hollowpurple|pooh": "虛式茈 完勝，小熊維尼 招都沒出完。",
            "hollowpurple|ronaldo": "C羅：不比了。",
            "hollowpurple|virus": "虛式茈 一招收工，病毒 GG。",
            "hollowpurple|shark": "鯊魚：不比了。",
            "hollowpurple|ufo": "飛碟 對上 虛式茈，秒退。",
            "hollowpurple|vampire": "虛式茈 完勝，吸血鬼 招都沒出完。",
            "hollowpurple|banana": "香蕉：不比了。",
            "hollowpurple|kitten": "沒懸念，虛式茈 輾過 小貓。",
            "hollowpurple|rock": "沒懸念，虛式茈 輾過 石頭。",
            "hollowpurple|scissors": "剪刀 對上 虛式茈，秒退。",
            "hollowpurple|paper": "這場 虛式茈 躺著贏。",
            "hollowpurple|lizard": "這場 虛式茈 躺著贏。",
            "hollowpurple|spock": "虛式茈 一招收工，史巴克 GG。",
            "chickenbro|love": "雞哥擁有很多愛。",
            "chickenbro|peterpan": "彼得潘被雞哥的鐵山靠撞飛。",
            "chickenbro|ronaldo": "這場 雞哥 躺著贏。",
            "chickenbro|banana": "這場 雞哥 躺著贏。",
            "chickenbro|kitten": "雞哥 一招收工，小貓 GG。",
            "chickenbro|rock": "雞哥 一招收工，石頭 GG。",
            "chickenbro|scissors": "剪刀：打不過 雞哥。",
            "chickenbro|paper": "布：不比了。",
            "chickenbro|lizard": "雞哥 出手，蜥蜴 直接沒了。",
            "pooh|godzilla": "哥吉拉遭到封殺",
            "pooh|nuke": "小熊維尼擁有超多核彈。",
            "pooh|love": "小熊維尼感受不到愛。",
            "pooh|peterpan": "彼得潘被小熊維尼封殺了。",
            "pooh|chickenbro": "小熊維尼登場，雞哥……你懂的。",
            "pooh|banana": "香蕉 對上 小熊維尼，秒退。",
            "pooh|kitten": "小貓：不比了。",
            "pooh|rock": "石頭：不比了。",
            "pooh|scissors": "小熊維尼 完勝，剪刀 招都沒出完。",
            "pooh|paper": "布：打不過 小熊維尼。",
            "pooh|lizard": "蜥蜴：打不過 小熊維尼。",
            "ronaldo|love": "C羅擁有很多愛。",
            "ronaldo|pooh": "沒懸念，C羅 輾過 小熊維尼。",
            "ronaldo|kitten": "C羅 出手，小貓 直接沒了。",
            "ronaldo|rock": "C羅 出手，石頭 直接沒了。",
            "ronaldo|scissors": "剪刀：不比了。",
            "ronaldo|paper": "這場 C羅 躺著贏。",
            "ronaldo|lizard": "C羅 一招收工，蜥蜴 GG。",
            "virus|godzilla": "哥吉拉被感染了。",
            "virus|chickenbro": "雞哥 對上 病毒，秒退。",
            "virus|pooh": "小熊維尼 被 病毒 打到懷疑人生。",
            "virus|ronaldo": "C羅：打不過 病毒。",
            "virus|shark": "鯊魚：打不過 病毒。",
            "virus|vampire": "吸血鬼 被 病毒 打到懷疑人生。",
            "virus|banana": "香蕉：打不過 病毒。",
            "virus|kitten": "這場 病毒 躺著贏。",
            "virus|rock": "這場 病毒 躺著贏。",
            "virus|scissors": "剪刀 被 病毒 打到懷疑人生。",
            "virus|paper": "病毒 完勝，布 招都沒出完。",
            "virus|lizard": "沒懸念，病毒 輾過 蜥蜴。",
            "virus|spock": "病毒 完勝，史巴克 招都沒出完。",
            "shark|chickenbro": "這場 鯊魚 躺著贏。",
            "shark|pooh": "沒懸念，鯊魚 輾過 小熊維尼。",
            "shark|ronaldo": "鯊魚 出手，C羅 直接沒了。",
            "shark|banana": "鯊魚 出手，香蕉 直接沒了。",
            "shark|rock": "鯊魚 完勝，石頭 招都沒出完。",
            "shark|scissors": "沒懸念，鯊魚 輾過 剪刀。",
            "shark|paper": "這場 鯊魚 躺著贏。",
            "shark|lizard": "鯊魚：這也算對手？",
            "ufo|godzilla": "哥吉拉被打包帶走。",
            "ufo|nuke": "太空科技勝出。",
            "ufo|love": "飛碟沒感覺。",
            "ufo|peterpan": "彼得潘打不過飛碟。",
            "ufo|chickenbro": "雞哥：打不過 飛碟。",
            "ufo|pooh": "小熊維尼：不比了。",
            "ufo|ronaldo": "沒懸念，飛碟 輾過 C羅。",
            "ufo|virus": "飛碟：這也算對手？",
            "ufo|shark": "沒懸念，飛碟 輾過 鯊魚。",
            "ufo|vampire": "飛碟 完勝，吸血鬼 招都沒出完。",
            "ufo|banana": "沒懸念，飛碟 輾過 香蕉。",
            "ufo|kitten": "飛碟 出手，小貓 直接沒了。",
            "ufo|rock": "飛碟 出手，石頭 直接沒了。",
            "ufo|scissors": "剪刀：不比了。",
            "ufo|paper": "布：打不過 飛碟。",
            "ufo|lizard": "飛碟 一招收工，蜥蜴 GG。",
            "ufo|spock": "飛碟 一招收工，史巴克 GG。",
            "vampire|peterpan": "吸血鬼：這也算對手？",
            "vampire|chickenbro": "這場 吸血鬼 躺著贏。",
            "vampire|pooh": "小熊維尼：不比了。",
            "vampire|ronaldo": "吸血鬼 出手，C羅 直接沒了。",
            "vampire|shark": "吸血鬼 出手，鯊魚 直接沒了。",
            "vampire|banana": "吸血鬼 出手，香蕉 直接沒了。",
            "vampire|kitten": "吸血鬼 完勝，小貓 招都沒出完。",
            "vampire|rock": "吸血鬼 完勝，石頭 招都沒出完。",
            "vampire|scissors": "沒懸念，吸血鬼 輾過 剪刀。",
            "vampire|paper": "吸血鬼：這也算對手？",
            "vampire|lizard": "吸血鬼：這也算對手？",
            "banana|godzilla": "哥吉拉踩到香蕉皮，滑倒，出局。",
            "banana|love": "香蕉感受不到愛。",
            "banana|ronaldo": "C羅踩到香蕉皮，直接自爆。",
            "banana|rock": "香蕉 完勝，石頭 招都沒出完。",
            "banana|scissors": "沒懸念，香蕉 輾過 剪刀。",
            "banana|paper": "這場 香蕉 躺著贏。",
            "banana|lizard": "香蕉：這也算對手？",
            "kitten|love": "小貓擁有很多愛。",
            "kitten|shark": "小貓喵一聲，鯊魚：下不了口。",
            "kitten|banana": "小貓 出手，香蕉 直接沒了。",
            "kitten|rock": "小貓 完勝，石頭 招都沒出完。",
            "kitten|scissors": "沒懸念，小貓 輾過 剪刀。",
            "kitten|paper": "小貓 一招收工，布 GG。",
            "kitten|lizard": "小貓：這也算對手？",
            "rock|love": "石頭感受不到愛。",
            "rock|scissors": "石頭一砸，剪刀變廢鐵。",
            "rock|lizard": "蜥蜴還沒逃，被石頭壓成標本。",
            "scissors|love": "剪刀感受不到愛。",
            "scissors|paper": "喀嚓，布被剪成兩半。",
            "scissors|lizard": "剪刀出手，蜥蜴斷頭退場。",
            "paper|love": "布感受不到愛。",
            "paper|rock": "石頭再硬，也被布包走。",
            "paper|spock": "一張紙寫滿反駁，史巴克無話可說。",
            "lizard|paper": "蜥蜴：布？午餐而已。",
            "lizard|spock": "蜥蜴一口咬下，史巴克中毒倒地。",
            "spock|peterpan": "彼得潘被史巴克融化。",
            "spock|chickenbro": "雞哥 對上 史巴克，秒退。",
            "spock|pooh": "小熊維尼：打不過 史巴克。",
            "spock|ronaldo": "C羅：打不過 史巴克。",
            "spock|shark": "鯊魚：打不過 史巴克。",
            "spock|vampire": "史巴克：這也算對手？",
            "spock|banana": "香蕉：打不過 史巴克。",
            "spock|kitten": "這場 史巴克 躺著贏。",
            "spock|rock": "相位槍一發，石頭汽化。",
            "spock|scissors": "史巴克隨手一敲，剪刀碎裂。",
        ]
    )
}
